export type UserRole = "PATIENT" | "DOCTOR" | "HOSPITAL_ADMIN";
export interface Token { access_token: string; token_type: string; role: UserRole; user_id: number; }
export interface DoctorPublic { doctor_id: number; hospital_id: number; hospital_ids?: number[] | null; specialization_id: number | null; first_name: string; last_name: string; bio: string | null; qualifications: string | null; years_of_experience: number | null; photo_url: string | null; hospital_name?: string | null; specialization_name?: string | null; }
export interface Slot { slot_id: number; doctor_id: number; start_time: string; end_time: string; consultation_mode: "IN_PERSON" | "ONLINE"; status: "AVAILABLE" | "BOOKED" | "CANCELLED"; }
export interface Appointment { appointment_id: number; slot_id: number; doctor_id: number; patient_id: number; status: "SCHEDULED" | "COMPLETED" | "CANCELLED" | "NO_SHOW"; reason: string | null; start_time?: string | null; end_time?: string | null; consultation_mode?: "IN_PERSON" | "ONLINE" | null; }
export interface AppointmentDetail { appointment_id: number; slot_id: number; doctor_id: number; patient_id: number; status: "SCHEDULED" | "COMPLETED" | "CANCELLED" | "NO_SHOW"; reason: string | null; booked_at?: string | null; cancelled_at?: string | null; cancelled_by?: string | null; cancel_reason?: string | null; start_time?: string | null; end_time?: string | null; consultation_mode?: "IN_PERSON" | "ONLINE" | null; doctor_first_name?: string | null; doctor_last_name?: string | null; doctor_photo_url?: string | null; patient_first_name?: string | null; patient_last_name?: string | null; patient_avatar_url?: string | null; consultation_id?: number | null; treatment_id?: number | null; }
export interface TreatmentCase { treatment_id: number; patient_id: number; doctor_id: number; title: string; status: string; }
export interface Prescription { prescription_id: number; patient_id: number; doctor_id: number; drug_id: number; status: "ACTIVE" | "COMPLETED" | "DISCONTINUED"; dosage?: string | null; frequency?: string | null; route?: string | null; instructions?: string | null; start_date?: string | null; end_date?: string | null; duration_note?: string | null; supersedes_id?: number | null; }
export interface ConsultationRx { prescription_id: number; drug_id: number; dosage: string | null; frequency: string | null; route: string | null; start_date: string | null; end_date: string | null; duration_note: string | null; instructions: string | null; status: string; supersedes_id: number | null; }
export interface TimelineConsultation { consultation_id: number; appointment_id?: number; chief_complaint?: string | null; condition_status?: string | null; symptoms?: string | null; examination_notes?: string | null; vitals?: Record<string, string | number> | null; follow_up_plan?: string | null; created_at?: string | null; prescriptions?: ConsultationRx[]; }
export interface PatientProfile { patient_id: number; first_name: string; last_name: string; date_of_birth?: string | null; gender?: string | null; city?: string | null; avatar_url?: string | null; email?: string | null; phone?: string | null; }
export interface DoctorContact { doctor_id: number; first_name: string; last_name: string; photo_url?: string | null; email?: string | null; phone?: string | null; }
export interface VisitDetailed extends Appointment { doctor_first_name?: string | null; doctor_last_name?: string | null; doctor_photo_url?: string | null; doctor_email?: string | null; doctor_phone?: string | null; patient_first_name?: string | null; patient_last_name?: string | null; patient_avatar_url?: string | null; patient_email?: string | null; patient_phone?: string | null; }
export interface Hospital { hospital_id: number; name: string; city: string | null; address?: string | null; phone?: string | null; email?: string | null; }
export interface Specialization { specialization_id: number; name: string; }
export interface Drug { drug_id: number; name: string; strength: string | null; image_url: string | null; generic_name?: string | null; form?: string | null; description?: string | null; }
export interface Message { message_id: number; sender_id: number; body: string | null; sent_at: string; }
export interface DoctorReview { review_id: number; appointment_id: number; doctor_id: number; patient_id: number; rating: number; comment: string | null; }
export interface DoctorReviews { average_rating: number | null; review_count: number; reviews: { review_id: number; appointment_id: number; rating: number; comment: string | null; created_at: string | null }[]; }
